[bigdata]
devops-1 ansible_host=192.168.122.202

[pipeline]
devops-2 ansible_host=192.168.122.46

[monitoring]
devops-3 ansible_host=192.168.122.126

[simulator]
devops-4 ansible_host=192.168.122.30

[all:vars]
ansible_user=marcos
ansible_ssh_private_key_file=~/.ssh/devops_lab
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3