[bigdata]
devops-1 ansible_host=192.168.122.200

[pipeline]
devops-2 ansible_host=192.168.122.231

[monitoring]
devops-3 ansible_host=192.168.122.40

[simulator]
devops-4 ansible_host=192.168.122.50

[all:vars]
ansible_user=marcos
ansible_ssh_private_key_file=~/.ssh/devops_lab
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3